from homeassistant.const import CONF_NAME

DOMAIN = "deltainverter"
DEFAULT_UPDATE_INTERVAL = 20

ATTRIBUTES = {
    "SAP Part Number": {"unit": "", "device_class": None},
    "SAP Serial Number": {"unit": "", "device_class": None},
    "SAP Date Code": {"unit": "", "device_class": None},
    "SAP Revision": {"unit": "", "device_class": None},
    "Software Revision AC Control": {"unit": "", "device_class": None},
    "Software Revision DC Control": {"unit": "", "device_class": None},
    "Software Revision Display": {"unit": "", "device_class": None},
    "Software Revision ENS Control": {"unit": "", "device_class": None},
    "Solar Current at Input 1": {"unit": "A", "device_class": "current"},
    "Solar Voltage at Input 1": {"unit": "V", "device_class": "voltage"},
    "Solar Isolation Resistance at Input 1": {"unit": "Ω", "device_class": "resistance"},
    "Solar Current at Input 2": {"unit": "A", "device_class": "current"},
    "Solar Voltage at Input 2": {"unit": "V", "device_class": "voltage"},
    "Solar Isolation Resistance at Input 2": {"unit": "Ω", "device_class": "resistance"},
    "AC Current": {"unit": "A", "device_class": "current"},
    "AC Voltage": {"unit": "V", "device_class": "voltage"},
    "AC Power": {"unit": "W", "device_class": "power"},
    "AC Frequency": {"unit": "Hz", "device_class": "frequency"},
    "Supplied AC Energy": {"unit": "kWh", "device_class": "energy"},
    "Inverter Runtime": {"unit": "hours", "device_class": "duration"},
    "Calculated Temperature at NTC (DC Side)": {"unit": "°C", "device_class": "temperature"},
    "Solar Input 1 MOV Resistance": {"unit": "Ω", "device_class": "resistance"},
    "Solar Input 2 MOV Resistance": {"unit": "Ω", "device_class": "resistance"},
    "Calculated Temperature at NTC (AC Side)": {"unit": "°C", "device_class": "temperature"},
    "AC Voltage (AC Control)": {"unit": "V", "device_class": "voltage"},
    "AC Frequency (AC Control)": {"unit": "Hz", "device_class": "frequency"},
    "DC Injection Current (AC Control)": {"unit": "A", "device_class": "current"},
    "AC Voltage (ENS Control)": {"unit": "V", "device_class": "voltage"},
    "AC Frequency (ENS Control)": {"unit": "Hz", "device_class": "frequency"},
    "DC Injection Current (ENS Control)": {"unit": "A", "device_class": "current"},
    "Maximum Solar 1 Input Current": {"unit": "A", "device_class": "current"},
    "Maximum Solar 1 Input Voltage": {"unit": "V", "device_class": "voltage"},
    "Maximum Solar 1 Input Power": {"unit": "W", "device_class": "power"},
    "Minimum Isolation Resistance Solar 1": {"unit": "Ω", "device_class": "resistance"},
    "Maximum Isolation Resistance Solar 1": {"unit": "Ω", "device_class": "resistance"},
    "Maximum Solar 2 Input Current": {"unit": "A", "device_class": "current"},
    "Maximum Solar 2 Input Voltage": {"unit": "V", "device_class": "voltage"},
    "Maximum Solar 2 Input Power": {"unit": "W", "device_class": "power"},
    "Minimum Isolation Resistance Solar 2": {"unit": "Ω", "device_class": "resistance"},
    "Maximum Isolation Resistance Solar 2": {"unit": "Ω", "device_class": "resistance"},
    "Maximum AC Current of Today": {"unit": "A", "device_class": "current"},
    "Minimum AC Voltage of Today": {"unit": "V", "device_class": "voltage"},
    "Maximum AC Voltage of Today": {"unit": "V", "device_class": "voltage"},
    "Maximum AC Power of Today": {"unit": "W", "device_class": "power"},
    "Minimum AC Frequency of Today": {"unit": "Hz", "device_class": "frequency"},
    "Maximum AC Frequency of Today": {"unit": "Hz", "device_class": "frequency"},
    "Global Alarm Status": {"unit": "", "device_class": None},
    "Status DC Input": {"unit": "", "device_class": None},
    "Limits DC Input": {"unit": "", "device_class": None},
    "Status AC Output": {"unit": "", "device_class": None},
    "Limits AC Output": {"unit": "", "device_class": None},
    "Isolation Warning Status": {"unit": "", "device_class": None},
    "DC Hardware Failure": {"unit": "", "device_class": None},
    "AC Hardware Failure": {"unit": "", "device_class": None},
    "ENS Hardware Failure": {"unit": "", "device_class": None},
    "Internal Bulk Failure": {"unit": "", "device_class": None},
    "Internal Communications Failure": {"unit": "", "device_class": None},
    "AC Hardware Disturbance": {"unit": "", "device_class": None}
}
