from homeassistant.const import CONF_NAME

DOMAIN = "deltainverter"
DEFAULT_UPDATE_INTERVAL = 20

ATTRIBUTES = {
    #"sap_part_number": {"friendly_name":"SAP Part Number","unit_of_measurement": "", "device_class": None},
    #"sap_serial_number": {"friendly_name":"SAP Serial Number","unit_of_measurement": "", "device_class": None},
    #"sap_date_code": {"friendly_name":"SAP Date Code","unit_of_measurement": "", "device_class": None},
    #"sap_revision": {"friendly_name":"SAP Revision","unit_of_measurement": "", "device_class": None},
    #"software_revision_ac_control": {"friendly_name":"Software Revision AC Control","unit_of_measurement": "", "device_class": None},
    #"software_revision_dc_control": {"friendly_name":"Software Revision DC Control","unit_of_measurement": "", "device_class": None},
    #"software_revision_display": {"friendly_name":"Software Revision Display","unit_of_measurement": "", "device_class": None},
    #"software_revision_ens_control": {"friendly_name":"Software Revision ENS Control","unit_of_measurement": "", "device_class": None},
    "solar_current_at_input_1": {"friendly_name":"Solar Current at Input 1","unit_of_measurement": "A", "device_class": "current"},
    "solar_voltage_at_input_1": {"friendly_name":"Solar Voltage at Input 1","unit_of_measurement": "V", "device_class": "voltage"},
    "solar_isolation_resistance_at_input_1": {"friendly_name":"Solar Isolation Resistance at Input 1","unit_of_measurement": "Ω", "device_class": "resistance"},
    "solar_current_at_input_2": {"friendly_name":"Solar Current at Input 2","unit_of_measurement": "A", "device_class": "current"},
    "solar_voltage_at_input_2": {"friendly_name":"Solar Voltage at Input 2","unit_of_measurement": "V", "device_class": "voltage"},
    "solar_isolation_resistance_at_input_2": {"friendly_name":"Solar Isolation Resistance at Input 2","unit_of_measurement": "Ω", "device_class": "resistance"},
    "ac_current": {"friendly_name":"AC Current","unit_of_measurement": "A", "device_class": "current"},
    "ac_voltage": {"friendly_name":"AC Voltage","unit_of_measurement": "V", "device_class": "voltage"},
    "ac_power": {"friendly_name":"AC Power","unit_of_measurement": "W", "device_class": "power"},
    "ac_frequency": {"friendly_name":"AC Frequency","unit_of_measurement": "Hz", "device_class": "frequency"},
    "supplied_ac_energy": {"friendly_name":"Supplied AC Energy","unit_of_measurement": "kWh", "device_class": "energy"},
    "inverter_runtime": {"friendly_name":"Inverter Runtime","unit_of_measurement": "hours", "device_class": "duration"},
    "calculated_temperature_at_ntc_dc_side": {"friendly_name":"Calculated Temperature at NTC (DC Side)","unit_of_measurement": "°C", "device_class": "temperature"},
    "solar_input_1_mov_resistance": {"friendly_name":"Solar Input 1 MOV Resistance","unit_of_measurement": "Ω", "device_class": "resistance"},
    "solar_input_2_mov_resistance": {"friendly_name":"Solar Input 2 MOV Resistance","unit_of_measurement": "Ω", "device_class": "resistance"},
    "calculated_temperature_at_ntc_ac_side": {"friendly_name":"Calculated Temperature at NTC (AC Side)","unit_of_measurement": "°C", "device_class": "temperature"},
    "ac_voltage_ac_control": {"friendly_name":"AC Voltage (AC Control)","unit_of_measurement": "V", "device_class": "voltage"},
    "ac_frequency_ac_control": {"friendly_name":"AC Frequency (AC Control)","unit_of_measurement": "Hz", "device_class": "frequency"},
    "dc_injection_current_ac_control": {"friendly_name":"DC Injection Current (AC Control)","unit_of_measurement": "A", "device_class": "current"},
    "ac_voltage_ens_control": {"friendly_name":"AC Voltage (ENS Control)","unit_of_measurement": "V", "device_class": "voltage"},
    "ac_frequency_ens_control": {"friendly_name":"AC Frequency (ENS Control)","unit_of_measurement": "Hz", "device_class": "frequency"},
    "dc_injection_current_ens_control": {"friendly_name":"DC Injection Current (ENS Control)","unit_of_measurement": "A", "device_class": "current"},
    "maximum_solar_1_input_current": {"friendly_name":"Maximum Solar 1 Input Current","unit_of_measurement": "A", "device_class": "current"},
    "maximum_solar_1_input_voltage": {"friendly_name":"Maximum Solar 1 Input Voltage","unit_of_measurement": "V", "device_class": "voltage"},
    "maximum_solar_1_input_power": {"friendly_name":"Maximum Solar 1 Input Power","unit_of_measurement": "W", "device_class": "power"},
    "minimum_isolation_resistance_solar_1": {"friendly_name":"Minimum Isolation Resistance Solar 1","unit_of_measurement": "Ω", "device_class": "resistance"},
    "maximum_isolation_resistance_solar_1": {"friendly_name":"Maximum Isolation Resistance Solar 1","unit_of_measurement": "Ω", "device_class": "resistance"},
    "maximum_solar_2_input_current": {"friendly_name":"Maximum Solar 2 Input Current","unit_of_measurement": "A", "device_class": "current"},
    "maximum_solar_2_input_voltage": {"friendly_name":"Maximum Solar 2 Input Voltage","unit_of_measurement": "V", "device_class": "voltage"},
    "maximum_solar_2_input_power": {"friendly_name":"Maximum Solar 2 Input Power","unit_of_measurement": "W", "device_class": "power"},
    "minimum_isolation_resistance_solar_2": {"friendly_name":"Minimum Isolation Resistance Solar 2","unit_of_measurement": "Ω", "device_class": "resistance"},
    "maximum_isolation_resistance_solar_2": {"friendly_name":"Maximum Isolation Resistance Solar 2","unit_of_measurement": "Ω", "device_class": "resistance"},
    "maximum_ac_current_of_today": {"friendly_name":"Maximum AC Current of Today","unit_of_measurement": "A", "device_class": "current"},
    "minimum_ac_voltage_of_today": {"friendly_name":"Minimum AC Voltage of Today","unit_of_measurement": "V", "device_class": "voltage"},
    "maximum_ac_voltage_of_today": {"friendly_name":"Maximum AC Voltage of Today","unit_of_measurement": "V", "device_class": "voltage"},
    "maximum_ac_power_of_today": {"friendly_name":"Maximum AC Power of Today","unit_of_measurement": "W", "device_class": "power"},
    "minimum_ac_frequency_of_today": {"friendly_name":"Minimum AC Frequency of Today","unit_of_measurement": "Hz", "device_class": "frequency"},
    "maximum_ac_frequency_of_today": {"friendly_name":"Maximum AC Frequency of Today","unit_of_measurement": "Hz", "device_class": "frequency"},
    "global_alarm_status": {"friendly_name":"Global Alarm Status","unit_of_measurement": "", "device_class": None},
    "status_dc_input": {"friendly_name":"Status DC Input","unit_of_measurement": "", "device_class": None},
    "limits_dc_input": {"friendly_name":"Limits DC Input","unit_of_measurement": "", "device_class": None},
    "status_ac_output": {"friendly_name":"Status AC Output","unit_of_measurement": "", "device_class": None},
    "limits_ac_output": {"friendly_name":"Limits AC Output","unit_of_measurement": "", "device_class": None},
    "isolation_warning_status": {"friendly_name":"Isolation Warning Status","unit_of_measurement": "", "device_class": None},
    "dc_hardware_failure": {"friendly_name":"DC Hardware Failure","unit_of_measurement": "", "device_class": None},
    "ac_hardware_failure": {"friendly_name":"AC Hardware Failure","unit_of_measurement": "", "device_class": None},
    "ens_hardware_failure": {"friendly_name":"ENS Hardware Failure","unit_of_measurement": "", "device_class": None},
    "internal_bulk_failure": {"friendly_name":"Internal Bulk Failure","unit_of_measurement": "", "device_class": None},
    "internal_communications_failure": {"friendly_name":"Internal Communications Failure","unit_of_measurement": "", "device_class": None},
    "ac_hardware_disturbance": {"friendly_name":"AC Hardware Disturbance","unit_of_measurement": "", "device_class": None}
}

