from homeassistant.const import CONF_NAME

DOMAIN = "deltainverter"
DEFAULT_UPDATE_INTERVAL = 20

ATTRIBUTES = {
    "SAP Part Number": {"friendly_name":"SAP Part Number","unit": "", "device_class": None},
    "SAP Serial Number": {"friendly_name":"SAP Serial Number","unit": "", "device_class": None},
    "SAP Date Code": {"friendly_name":"SAP Date Code","unit": "", "device_class": None},
    "SAP Revision": {"friendly_name":"SAP Revision","unit": "", "device_class": None},
    "Software Revision AC Control": {"friendly_name":"Software Revision AC Control","unit": "", "device_class": None},
    "Software Revision DC Control": {"friendly_name":"Software Revision DC Control","unit": "", "device_class": None},
    "Software Revision Display": {"friendly_name":"Software Revision Display","unit": "", "device_class": None},
    "Software Revision ENS Control": {"friendly_name":"Software Revision ENS Control","unit": "", "device_class": None},
    "Solar Current at Input 1": {"friendly_name":"Solar Current at Input 1","unit": "A", "device_class": "current"},
    "Solar Voltage at Input 1": {"friendly_name":"Solar Voltage at Input 1","unit": "V", "device_class": "voltage"},
    "Solar Isolation Resistance at Input 1": {"friendly_name":"Solar Isolation Resistance at Input 1","unit": "Ω", "device_class": "resistance"},
    "Solar Current at Input 2": {"friendly_name":"Solar Current at Input 2","unit": "A", "device_class": "current"},
    "Solar Voltage at Input 2": {"friendly_name":"Solar Voltage at Input 2","unit": "V", "device_class": "voltage"},
    "Solar Isolation Resistance at Input 2": {"friendly_name":"Solar Isolation Resistance at Input 2","unit": "Ω", "device_class": "resistance"},
    "AC Current": {"friendly_name":"AC Current","unit": "A", "device_class": "current"},
    "AC Voltage": {"friendly_name":"AC Voltage","unit": "V", "device_class": "voltage"},
    "AC Power": {"friendly_name":"AC Power","unit": "W", "device_class": "power"},
    "AC Frequency": {"friendly_name":"AC Frequency","unit": "Hz", "device_class": "frequency"},
    "Supplied AC Energy": {"friendly_name":"Supplied AC Energy","unit": "kWh", "device_class": "energy"},
    "Inverter Runtime": {"friendly_name":"Inverter Runtime","unit": "hours", "device_class": "duration"},
    "Calculated Temperature at NTC (DC Side)": {"friendly_name":"Calculated Temperature at NTC (DC Side)","unit": "°C", "device_class": "temperature"},
    "Solar Input 1 MOV Resistance": {"friendly_name":"Solar Input 1 MOV Resistance","unit": "Ω", "device_class": "resistance"},
    "Solar Input 2 MOV Resistance": {"friendly_name":"Solar Input 2 MOV Resistance","unit": "Ω", "device_class": "resistance"},
    "Calculated Temperature at NTC (AC Side)": {"friendly_name":"Calculated Temperature at NTC (AC Side)","unit": "°C", "device_class": "temperature"},
    "AC Voltage (AC Control)": {"friendly_name":"AC Voltage (AC Control)","unit": "V", "device_class": "voltage"},
    "AC Frequency (AC Control)": {"friendly_name":"AC Frequency (AC Control)","unit": "Hz", "device_class": "frequency"},
    "DC Injection Current (AC Control)": {"friendly_name":"DC Injection Current (AC Control)","unit": "A", "device_class": "current"},
    "AC Voltage (ENS Control)": {"friendly_name":"AC Voltage (ENS Control)","unit": "V", "device_class": "voltage"},
    "AC Frequency (ENS Control)": {"friendly_name":"AC Frequency (ENS Control)","unit": "Hz", "device_class": "frequency"},
    "DC Injection Current (ENS Control)": {"friendly_name":"DC Injection Current (ENS Control)","unit": "A", "device_class": "current"},
    "Maximum Solar 1 Input Current": {"friendly_name":"Maximum Solar 1 Input Current","unit": "A", "device_class": "current"},
    "Maximum Solar 1 Input Voltage": {"friendly_name":"Maximum Solar 1 Input Voltage","unit": "V", "device_class": "voltage"},
    "Maximum Solar 1 Input Power": {"friendly_name":"Maximum Solar 1 Input Power","unit": "W", "device_class": "power"},
    "Minimum Isolation Resistance Solar 1": {"friendly_name":"Minimum Isolation Resistance Solar 1","unit": "Ω", "device_class": "resistance"},
    "Maximum Isolation Resistance Solar 1": {"friendly_name":"Maximum Isolation Resistance Solar 1","unit": "Ω", "device_class": "resistance"},
    "Maximum Solar 2 Input Current": {"friendly_name":"Maximum Solar 2 Input Current","unit": "A", "device_class": "current"},
    "Maximum Solar 2 Input Voltage": {"friendly_name":"Maximum Solar 2 Input Voltage","unit": "V", "device_class": "voltage"},
    "Maximum Solar 2 Input Power": {"friendly_name":"Maximum Solar 2 Input Power","unit": "W", "device_class": "power"},
    "Minimum Isolation Resistance Solar 2": {"friendly_name":"Minimum Isolation Resistance Solar 2","unit": "Ω", "device_class": "resistance"},
    "Maximum Isolation Resistance Solar 2": {"friendly_name":"Maximum Isolation Resistance Solar 2","unit": "Ω", "device_class": "resistance"},
    "Maximum AC Current of Today": {"friendly_name":"Maximum AC Current of Today","unit": "A", "device_class": "current"},
    "Minimum AC Voltage of Today": {"friendly_name":"Minimum AC Voltage of Today","unit": "V", "device_class": "voltage"},
    "Maximum AC Voltage of Today": {"friendly_name":"Maximum AC Voltage of Today","unit": "V", "device_class": "voltage"},
    "Maximum AC Power of Today": {"friendly_name":"Maximum AC Power of Today","unit": "W", "device_class": "power"},
    "Minimum AC Frequency of Today": {"friendly_name":"Minimum AC Frequency of Today","unit": "Hz", "device_class": "frequency"},
    "Maximum AC Frequency of Today": {"friendly_name":"Maximum AC Frequency of Today","unit": "Hz", "device_class": "frequency"},
    "Global Alarm Status": {"friendly_name":"Global Alarm Status","unit": "", "device_class": None},
    "Status DC Input": {"friendly_name":"Status DC Input","unit": "", "device_class": None},
    "Limits DC Input": {"friendly_name":"Limits DC Input","unit": "", "device_class": None},
    "Status AC Output": {"friendly_name":"Status AC Output","unit": "", "device_class": None},
    "Limits AC Output": {"friendly_name":"Limits AC Output","unit": "", "device_class": None},
    "Isolation Warning Status": {"friendly_name":"Isolation Warning Status","unit": "", "device_class": None},
    "DC Hardware Failure": {"friendly_name":"DC Hardware Failure","unit": "", "device_class": None},
    "AC Hardware Failure": {"friendly_name":"AC Hardware Failure","unit": "", "device_class": None},
    "ENS Hardware Failure": {"friendly_name":"ENS Hardware Failure","unit": "", "device_class": None},
    "Internal Bulk Failure": {"friendly_name":"Internal Bulk Failure","unit": "", "device_class": None},
    "Internal Communications Failure": {"friendly_name":"Internal Communications Failure","unit": "", "device_class": None},
    "AC Hardware Disturbance": {"friendly_name":"AC Hardware Disturbance","unit": "", "device_class": None}
}
